Repository durgesh2001/Hacktoberfest_2022, pull requests merged in 2022-10, with the labels that each got.

#5 College Project Added
  loginadmin/build/classes/com/college/dao/Database.class
  loginadmin/build/classes/com/college/dao/package-info.class
  loginadmin/build/classes/com/college/entity/collegeentity.class
  loginadmin/build/classes/com/college/entity/package-info.class
  loginadmin/build/classes/loginadmin/package-info.class
  loginadmin/build/classes/loginadmin/userprocess.class
  loginadmin/database/data.sql
  loginadmin/src/main/java/com/college/dao/Database.java
  loginadmin/src/main/java/com/college/dao/package-info.java
  loginadmin/src/main/java/com/college/entity/collegeentity.java
  loginadmin/src/main/java/com/college/entity/package-info.java
  loginadmin/src/main/java/loginadmin/package-info.java
  loginadmin/src/main/java/loginadmin/userprocess.java
  loginadmin/src/main/webapp/AdminLogo.png
  loginadmin/src/main/webapp/CSS/style.css
  loginadmin/src/main/webapp/META-INF/MANIFEST.MF
  loginadmin/src/main/webapp/StudentLogo.png
  loginadmin/src/main/webapp/TeacherLogo.png
  loginadmin/src/main/webapp/WEB-INF/lib/jakarta-servlet-api-4.jar
  loginadmin/src/main/webapp/WEB-INF/lib/jsp-api.jar
  loginadmin/src/main/webapp/WEB-INF/lib/jstl-1.2.jar
  loginadmin/src/main/webapp/WEB-INF/lib/mysql-connector-java-8.0.30.jar
  loginadmin/src/main/webapp/WEB-INF/lib/servlet-api-2.5.jar
  loginadmin/src/main/webapp/WEB-INF/web.xml
  loginadmin/src/main/webapp/admincourse.jsp
  loginadmin/src/main/webapp/admindashboard.jsp
  loginadmin/src/main/webapp/adminfaculty.jsp
  loginadmin/src/main/webapp/adminlogin.jsp
  loginadmin/src/main/webapp/adminstudent.jsp
  loginadmin/src/main/webapp/adminsubject.jsp
  loginadmin/src/main/webapp/chooseuser.jsp
  loginadmin/src/main/webapp/delete.jsp
  loginadmin/src/main/webapp/deletef.jsp
  loginadmin/src/main/webapp/facultylogin.jsp
  loginadmin/src/main/webapp/logo.png
  loginadmin/src/main/webapp/pnotice.jsp
  loginadmin/src/main/webapp/process.jsp
  loginadmin/src/main/webapp/process1.jsp
  loginadmin/src/main/webapp/process2.jsp
  loginadmin/src/main/webapp/process3.jsp
  loginadmin/src/main/webapp/process4.jsp
  loginadmin/src/main/webapp/process5.jsp
  loginadmin/src/main/webapp/sprocess.jsp
  loginadmin/src/main/webapp/studentassign.jsp
  loginadmin/src/main/webapp/studentdashboard.jsp
  loginadmin/src/main/webapp/studentlogin.jsp
  loginadmin/src/main/webapp/tassign.jsp
  loginadmin/src/main/webapp/teacherdashboard.jsp
  loginadmin/src/main/webapp/tpnotice.jsp
  loginadmin/src/main/webapp/tprocess.jsp
  loginadmin/src/main/webapp/tprocess1.jsp
  loginadmin/src/main/webapp/tprocess2.jsp
  loginadmin/src/main/webapp/update.jsp
  loginadmin/src/main/webapp/updatef.jsp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#7 Create library.cpp
  Library Simulation/library.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#6 parallax scrolling website designed added
  parallax scrolling/index.css
  parallax scrolling/index.html
  parallax scrolling/moon.png
  parallax scrolling/mountains_behind.png
  parallax scrolling/mountains_front.png
  parallax scrolling/night-beautiful-landscape-with-winter-city-trees-mountain-moon-shine-with-purple-moon-snow-violet-sky-landscape-background-your-arts_177886-7.jpg
  parallax scrolling/stars.png
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#10 added the folder css card
  CSS Card/card-img.jpg
  CSS Card/card.html
  CSS Card/style-card.css
  CSS Card/vanilla-tilt.js
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#13 Dictionary app
  Dictionary App/index.html
  Dictionary App/script.js
  Dictionary App/style.css
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#12 updated readme
  README.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#16 added "remove dupliactes from existing linked list"
  DSA/removeDuplicate.cpp
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#17 Creating CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: hacktoberfest-accepted, hacktoberfest2022

#22 Create Liquid_Swipe Animation
  Liquid_Swipe Animation
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#19 Added arrays simple manipulations
  Arrays_beginner/AlgorithmsToDo.md
  Arrays_beginner/Array_Insert.c
  Arrays_beginner/largest element of two
  Arrays_beginner/largest-element-in-array.c
  Arrays_beginner/reverse_array
  Arrays_beginner/smallest element
  Arrays_beginner/sum_of_array.c
  Arrays_beginner/two smallest element
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#21 Adds to do list project
  to-do-list/.gitignore
  to-do-list/index.html
  to-do-list/scripts/main.js
  to-do-list/styles/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#20 Hacktoberfest22
  DSA/removeDuplicate.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022

#23 Create Longest-Palindromic-Substring.py
  Longest-Palindromic-Substring.py
Labels: hacktoberfest-accepted, hacktoberfest

#25 Add files via upload
  Arrays_beginner/TrappingRainWater.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#24 Added colorGenerator
  colorGenerator/app.js
  colorGenerator/index.html
  colorGenerator/style.css
Labels: hacktoberfest-accepted

#32 hexadecimal to decimal
  Python/hexToDeci.py
Labels: hacktoberfest-accepted, hacktoberfest

#31 Added Triangle Generator python program
  python/palindrome.py
  python/triangle.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#29 add fibonacci series program
  Python/fibonacci.py
Labels: hacktoberfest-accepted

#27 Update style-card.css
  CSS Card/style-card.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#26 Create Binary Search
  DSA/Binary Search
Labels: hacktoberfest-accepted, hacktoberfest

#36 Add files via upload
  Dev C++/1-d array.cpp
  Dev C++/1-d array.exe
  Dev C++/1_inversionCount.cpp
  Dev C++/1_inversionCount.exe
  Dev C++/3x3 matrix.cpp
  Dev C++/3x3 matrix.exe
  Dev C++/DAA Merge sort.cpp
  Dev C++/DAA Merge sort.exe
  Dev C++/DAA Quick sort.cpp
  Dev C++/DAA Quick sort.exe
  Dev C++/Singly linked list.cpp
  Dev C++/Singly linked list.exe
  Dev C++/Swappimg.cpp
  Dev C++/Swappimg.exe
  Dev C++/Switch case two operands.cpp
  Dev C++/Switch case two operands.exe
  Dev C++/call by value.cpp
  Dev C++/call by value.exe
  Dev C++/circular linked list.cpp
  Dev C++/circular linked list.exe
  Dev C++/do while 1 to 10.cpp
  Dev C++/do while 1 to 10.exe
  Dev C++/doubly linked list.cpp
  Dev C++/doubly linked list.exe
  Dev C++/else if lader.cpp
  Dev C++/else if lader.exe
  Dev C++/equal of two no.cpp
  Dev C++/equal of two no.exe
  Dev C++/file handle.cpp
  Dev C++/file handle.exe
  Dev C++/file_handle.c
  Dev C++/for 1 to 10.cpp
  Dev C++/for 1 to 10.exe
  Dev C++/function.cpp
  Dev C++/function.exe
  Dev C++/greater number ternary.cpp
  Dev C++/greater number ternary.exe
  Dev C++/hello.cpp
  Dev C++/hello.exe
  Dev C++/nested for.cpp
  Dev C++/nested for.exe
  Dev C++/pointer.cpp
  Dev C++/pointer.exe
  Dev C++/prime.cpp
  Dev C++/prime.exe
  Dev C++/while 1 to 5.cpp
  Dev C++/while 1 to 5.exe
Labels: hacktoberfest-accepted, hacktoberfest2022

#46 decimal to binary python program
  Python/dec_to_bin.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#48 Glassmorphic Animated Calculator
  AnimatedCalculator/README.md
  AnimatedCalculator/eidt.css
  AnimatedCalculator/index.html
  AnimatedCalculator/vanilla-tilt.js
  Expense_Tracker/REAMDE.md
  Expense_Tracker/index.html
  Expense_Tracker/style.css
  Expense_Tracker/work.js
Labels: hacktoberfest-accepted, hacktoberfest2022

#45 Added String Java Code
  String Manipulation/PalindromeString.java
  String Manipulation/ReverseString.java
  String Manipulation/StringCaseChange.java
  String Manipulation/WordType.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#33 Added solutions to some more challenging problems
  DSA/dsa_hack/Knapsack DP Problem in Graph.txt
  DSA/dsa_hack/decimal_to_hexa.cpp.txt
  DSA/dsa_hack/even-and-odd.c.txt
  DSA/dsa_hack/unique-elements-in-an-array.c.txt
Labels: hacktoberfest-accepted, hacktoberfest2022

#43 Update card.html
  CSS Card/card.html
Labels: hacktoberfest-accepted, hacktoberfest2022

#42 Added reverse.py
  Python/reverse.py
Labels: hacktoberfest-accepted, hacktoberfest2022

#37 added Selection sort
  Dev C++/selectionSort.cpp
  Dev C++/selectionSort.exe
Labels: hacktoberfest-accepted, hacktoberfest2022

#34 feat(rust): add bubble sort
  rust/bubble_sort.rs
Labels: hacktoberfest-accepted, hacktoberfest

#35 I have added code for my introductory website.
  business-card/Bubble-Background.svg
  business-card/Live-Wave-Background-1/Live-Wave-Background/Informations.txt
  business-card/Live-Wave-Background.svg
  business-card/README.md
  business-card/Snow-Animation-Background.svg
  business-card/Snow-Animation-Background/Snow-Animation-Background/Informations.txt
  business-card/Snow-Animation-Background/Snow-Animation-Background/Snow-Animation-Background.svg
  business-card/images/per.png
  business-card/images/pfp-2.jpg
  business-card/index.html
  business-card/profile picture.png
  business-card/script.js
  business-card/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#51 Add files via upload
  index1.html
Labels: hacktoberfest-accepted, hacktoberfest2022

#59 Update index.html
  Expense_Tracker/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#49 Movie
  Movie_Website/README.md
  Movie_Website/css/style.css
  Movie_Website/film/edit.css
  Movie_Website/film/index.html
  Movie_Website/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#61 Hacktoberfest2022
  Instagramloginpageui/images/app store.png
  Instagramloginpageui/images/fb.png
  Instagramloginpageui/images/instagram logo.png
  Instagramloginpageui/images/play store.png
  Instagramloginpageui/index.html
  Instagramloginpageui/sign-up form.html
  Instagramloginpageui/sign-up.css
  Instagramloginpageui/style.css
Labels: hacktoberfest-accepted, hacktoberfest2022

#80 Html , CSS , Javascript project - Drawing_App
  Drawing_app/index.html
  Drawing_app/script.js
  Drawing_app/style.css
Labels: hacktoberfest-accepted

#78 added weather application
  web_server/package-lock.json
  web_server/package.json
  web_server/public/css/style.css
  web_server/public/img/canIHelpYou.png
  web_server/public/img/lost.jpg
  web_server/public/img/my_current_pic.jpg
  web_server/public/img/my_pic.jpg
  web_server/public/img/weather.png
  web_server/public/img/whatHappened.jpeg
  web_server/public/img/whatHappened.jpg
  web_server/public/js/app.js
  web_server/public/js/weather.js
  web_server/src/app.js
  web_server/src/style.css
  web_server/src/utils/forecast.js
  web_server/src/utils/geocode.js
  web_server/templates/partials/footer.hbs
  web_server/templates/partials/header.hbs
  web_server/templates/views/404.hbs
  web_server/templates/views/about.hbs
  web_server/templates/views/help.hbs
  web_server/templates/views/index.hbs
Labels: hacktoberfest-accepted

#75 Adding a 2-D CSS Game
  2D-MarioGame/assets/gifs/giphy (1).gif
  2D-MarioGame/assets/gifs/giphy (2).gif
  2D-MarioGame/assets/gifs/giphy (3).gif
  2D-MarioGame/assets/gifs/giphy (4).gif
  2D-MarioGame/assets/gifs/giphy (5).gif
  2D-MarioGame/assets/gifs/giphy (6).gif
  2D-MarioGame/assets/gifs/giphy.gif
  2D-MarioGame/assets/gifs/mar.gif
  2D-MarioGame/assets/images/814007_super-mario-backgrounds_1920x1200_h.png
  2D-MarioGame/assets/images/bg.jpg
  2D-MarioGame/html/boy.html
  2D-MarioGame/html/boyw.html
  2D-MarioGame/html/intro.html
  2D-MarioGame/html/intro2.html
  2D-MarioGame/html/mario.html
  2D-MarioGame/html/mariow.html
  2D-MarioGame/html/pokemon.html
  2D-MarioGame/html/pokemonw.html
  2D-MarioGame/html/runmario.html
  2D-MarioGame/html/sonic.html
  2D-MarioGame/html/sonicw.html
  2D-MarioGame/index.html
Labels: hacktoberfest-accepted

#94 Add files via upload
  aboutme.html
  blog.html
  contactus.html
  index1.html
  lap1.jpg
  sing.jpg
  sport.jpg
Labels: hacktoberfest-accepted
